CREATE VIEW dbo.vTBL_EXPENSES

as

SELECT 	 e.[DATE]
		,e.[NAME]
		,e.PRICE
		,ISNULL(c.CATEGORY, -1) AS CATEGORY
FROM dbo.TBL_EXPENSES AS e
LEFT JOIN dbo.DIC_CATEGORY AS c ON e.ID_CATEGORY = c.ID_CATEGORY
;